// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6EvQE3wD4D-qs1gIq-Zk6XvPurcrbjrY',
    appId: '1:1081594365878:web:512d54e56f35902b1ea317',
    messagingSenderId: '1081594365878',
    projectId: 'yoobbel-bbsr01',
    authDomain: 'yoobbel-bbsr01.firebaseapp.com',
    storageBucket: 'yoobbel-bbsr01.firebasestorage.app',
    measurementId: 'G-K8M4V8ZR1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrKSjEDerQjyxjDRSCQC9bvzU8KEA4QbU',
    appId: '1:1081594365878:android:23510363559189d81ea317',
    messagingSenderId: '1081594365878',
    projectId: 'yoobbel-bbsr01',
    storageBucket: 'yoobbel-bbsr01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJBh93b9sys9XKFbPfS_NaUhOb2UMlNwI',
    appId: '1:1081594365878:ios:373f4a270ef29e0d1ea317',
    messagingSenderId: '1081594365878',
    projectId: 'yoobbel-bbsr01',
    storageBucket: 'yoobbel-bbsr01.firebasestorage.app',
    iosBundleId: 'com.yoobbel.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJBh93b9sys9XKFbPfS_NaUhOb2UMlNwI',
    appId: '1:1081594365878:ios:b54953975b85d7a31ea317',
    messagingSenderId: '1081594365878',
    projectId: 'yoobbel-bbsr01',
    storageBucket: 'yoobbel-bbsr01.firebasestorage.app',
    iosBundleId: 'com.example.yoobbel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6EvQE3wD4D-qs1gIq-Zk6XvPurcrbjrY',
    appId: '1:1081594365878:web:18a11d5bc1bde3a61ea317',
    messagingSenderId: '1081594365878',
    projectId: 'yoobbel-bbsr01',
    authDomain: 'yoobbel-bbsr01.firebaseapp.com',
    storageBucket: 'yoobbel-bbsr01.firebasestorage.app',
    measurementId: 'G-6G87YQTYZ1',
  );
}
